services:
  - type: web
    name: nexora
    env: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn --config gunicorn.conf.py --timeout 120 --workers 2 --worker-class sync --max-requests 1000 --max-requests-jitter 100 --preload app.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: app.settings
      - key: DEBUG
        value: False
      - key: GEMINI_API_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: SECRET_KEY
        sync: false
